// constants/usernameParts.ts

export const adjectives: string[] = [
  'quirky', 'cosmic', 'silent', 'wandering', 'epic', 'frosty', 'golden', 'shadowy',
  'radiant', 'nimble', 'brave', 'clever', 'daring', 'eager', 'fearless', 'gentle',
  'happy', 'jolly', 'kind', 'lively', 'merry', 'noble', 'proud', 'silly', 'thankful',
  'witty', 'zany', 'atomic', 'binary', 'cyber', 'digital', 'electric', 'fuzzy',
  'giant', 'hidden', 'iron', 'jade', 'keen', 'lucky', 'magic', 'neon', 'omega',
  'pixel', 'quantum', 'retro', 'solar', 'turbo', 'ultra', 'vinyl', 'wizard',
  'xenon', 'yellow', 'zeta',
  'based', 'boujee', 'chad', 'cheugy', 'cringe', 'cursed', 'dank', 'drippy', 'extra',
  'faded', 'fire', 'ghosted', 'glowup', 'goated', 'grindy', 'iconic', 'iykyk',
  'legit', 'lowkey', 'moody', 'pog', 'salty', 'savage', 'shady', 'shook', 'simp',
  'slaps', 'slept', 'snatched', 'spicy', 'stan', 'sus', 'swaggy', 'thirsty',
  'vibey', 'viral', 'woke', 'yeet',
  'afk', 'brb', 'buffed', 'campy', 'clutch', 'cracked', 'farmed', 'gg', 'griefed',
  'inting', 'juiced', 'kappa', 'kinda', 'lfg', 'litty', 'lurking', 'meta', 'nerfed',
  'offline', 'online', 'op', 'poggers', 'pepega', 'raiding', 'rekt', 'smurfing',
  'sniped', 'toxic', 'tryhard', 'washed', 'zerg', 
  'ancient', 'arctic', 'azure', 'blazing', 'breezy', 'brisk', 'bubbly', 'calm',
  'cloudy', 'coastal', 'copper', 'coral', 'crimson', 'crystal', 'curly', 'cyan',
  'dapper', 'dawn', 'deep', 'delta', 'desert', 'dewy', 'dim', 'divine', 'dreamy',
  'drowsy', 'dusk', 'dusty', 'earthy', 'ebony', 'echo', 'emerald', 'empty',
  'eternal', 'faint', 'fancy', 'fiery', 'fluffy', 'fluid', 'foggy', 'forest',
  'fragrant', 'frozen', 'gilded', 'glassy', 'gloomy', 'grand', 'grape', 'gray',
  'green', 'groovy', 'hazy', 'heavenly', 'heavy', 'hollow', 'holy', 'honey',
  'icy', 'indigo', 'island', 'ivory', 'jungle', 'junior', 'lava', 'lemon',
  'liberty', 'lilac', 'lime', 'little', 'lunar', 'lush', 'magenta', 'maple',
  'marine', 'marshy', 'meadow', 'mellow', 'metal', 'mighty', 'milky', 'misty',
  'modern', 'molten', 'mossy', 'mountain', 'muddy', 'murky', 'muted', 'mystic',
  'narrow', 'naval', 'night', 'noisy', 'northern', 'oaken', 'oceanic', 'olive',
  'onyx', 'orange', 'orchid', 'outer', 'pale', 'pastel', 'patchy', 'peaceful',
  'peachy', 'pearly', 'pepper', 'petal', 'phantom', 'plain', 'placid', 'plump',
  'polar', 'posh', 'powder', 'primal', 'prism', 'proper', 'pulse', 'punchy',
  'pure', 'purple', 'pyro', 'quaint', 'quick', 'quiet', 'rainy', 'rapid', 'rare',
  'regal', 'rich', 'ripe', 'rising', 'river', 'roaring', 'rosy', 'royal', 'ruby',
  'rugged', 'rusty', 'sacred', 'sandy', 'sapphire', 'scarlet', 'scenic', 'serene',
  'severe', 'shady', 'shaky', 'sharp', 'shiny', 'short', 'silken', 'silver',
  'sky', 'sleepy', 'slight', 'slimy', 'slippery', 'slow', 'small', 'smoky',
  'smooth', 'snowy', 'snug', 'soapy', 'soft', 'solid', 'somber', 'soothing',
  'sour', 'southern', 'sparkly', 'speedy', 'spiffy', 'spiky', 'spirit', 'splashy',
  'spooky', 'spotty', 'spring', 'square', 'stable', 'stark', 'static', 'steady',
  'steel', 'steep', 'sticky', 'still', 'stone', 'stormy', 'straw', 'stream',
  'striped', 'sturdy', 'subtle', 'sugar', 'summer', 'sunny', 'super', 'swampy',
  'sweet', 'swift', 'tangled', 'tasty', 'tawny', 'teal', 'tender', 'tepid',
  'terra', 'tidal', 'tidy', 'timber', 'tiny', 'topaz', 'torch', 'torrid', 'toxic',
  'tranquil', 'tribal', 'tricky', 'tropical', 'truthful', 'tundra', 'twilight',
  'twin', 'umbra', 'unique', 'upland', 'urban', 'useful', 'usual', 'vague',
  'valiant', 'valid', 'vanilla', 'vast', 'velvet', 'vernal', 'vibrant', 'violet',
  'vista', 'vital', 'vivid', 'void', 'volcanic', 'warm', 'watery', 'wavy',
  'western', 'wheat', 'whimsy', 'white', 'whole', 'wicked', 'wide', 'wild',
  'windy', 'winter', 'wispy', 'wooden', 'woody', 'woolly', 'worldly', 'worn',
  'worthy', 'woven', 'young', 'yummy', 'zigzag'
];

export const nouns: string[] = [
  'ninja', 'robot', 'popcorn', 'llama', 'wizard', 'dragon', 'phoenix', 'comet',
  'galaxy', 'nebula', 'quasar', 'planet', 'star', 'moon', 'sun', 'asteroid',
  'meteor', 'alien', 'cyborg', 'android', 'droid', 'bot', 'computer', 'code',
  'pixel', 'byte', 'chip', 'circuit', 'console', 'joystick', 'keyboard', 'mouse',
  'screen', 'avatar', 'hero', 'villain', 'quest', 'level', 'score', 'token', 'gem',
  'key', 'map', 'portal', 'ship', 'rocket', 'laser', 'shield', 'sword', 'wand',
  'potion', 'scroll', 'book', 'meme', 'vibe', 'glitch', 'stream', 'troll', 'noob',
  'chad', 'karen', 'boomer','zoomer', 'emoji', 'hashtag', 'filter', 'influencer',
  'metaverse', 'nft','crypto', 'algorithm', 'bandwidth', 'cache', 'cloud', 'cookie',
  'domain', 'firewall', 'firmware', 'hardware', 'interface', 'malware', 'modem',
  'network', 'phishing', 'podcast', 'protocol', 'proxy', 'router', 'server',
  'software', 'spam', 'trojan', 'url', 'virus', 'webcam', 'widget', 'wifi',
  'wiki', 'zip', 'database',
  'anchor', 'apple', 'arrow', 'autumn', 'bamboo', 'banana', 'beacon', 'bean',
  'bear', 'beast', 'berry', 'blade', 'blossom', 'boulder', 'bow', 'branch',
  'bread', 'brook', 'bubble', 'bucket', 'bug', 'bull', 'butterfly', 'cactus',
  'cake', 'camel', 'candle', 'candy', 'canyon', 'cape', 'carrot', 'cart', 'cat',
  'cauldron', 'cave', 'chain', 'chair', 'chalk', 'charm', 'cheese', 'cherry',
  'chest', 'chili', 'chimney', 'cinnamon', 'clam', 'claw', 'clay', 'cliff',
  'cloak', 'clock', 'clover', 'clown', 'coal', 'cobra', 'coconut', 'coffee',
  'coin', 'compass', 'cone', 'coral', 'cork', 'corn', 'crab', 'crater', 'cream',
  'creek', 'crest', 'cricket', 'crown', 'crumb', 'crush', 'crust', 'crystal',
  'cube', 'cupcake', 'curry', 'cushion', 'dagger', 'daisy', 'dancer', 'dart',
  'dawn', 'deer', 'demon', 'denim', 'desert', 'diamond', 'dice', 'dingo', 'diver',
  'dog', 'doll', 'dolphin', 'donkey', 'dough', 'dove', 'dream', 'drift', 'drum',
  'duck', 'dune', 'dwarf', 'eagle', 'earth', 'eel', 'egg', 'elbow', 'element',
  'elephant', 'elf', 'elixir', 'ember', 'engine', 'envoy', 'epoch', 'essence',
  'eternity', 'ether', 'expert', 'eye', 'fabric', 'face', 'falcon', 'fang',
  'farm', 'feather', 'fern', 'ferret', 'fiddle', 'fig', 'finch', 'finger',
  'firefly', 'fish', 'fist', 'flag', 'flame', 'flare', 'flask', 'fleet', 'flesh',
  'flint', 'float', 'flock', 'flood', 'flour', 'flower', 'flute', 'fly', 'foam',
  'fog', 'foil', 'folk', 'food', 'fool', 'foot', 'forest', 'forge', 'fork',
  'form', 'fossil', 'fountain', 'fox', 'frame', 'freight', 'frenzy', 'frog',
  'frost', 'fruit', 'fury', 'fuse', 'gadget', 'gale', 'garlic', 'gate', 'gaze',
  'gecko', 'geese', 'genie', 'ghost', 'ghoul', 'giant', 'gift', 'ginger',
  'giraffe', 'glacier', 'glade', 'gland', 'glass', 'gleam', 'glide', 'glimmer',
  'globe', 'gloom', 'glove', 'gnome', 'goat', 'goblet', 'goblin', 'gold',
  'golem', 'goose', 'gopher', 'gorge', 'gorilla', 'gourd', 'grain', 'grape',
  'grass', 'grate', 'grave', 'grease', 'griffin', 'grill', 'grip', 'grit',
  'ground', 'grove', 'guard', 'guest', 'guide', 'gulf', 'gum', 'guru', 'gust',
  'gypsy', 'hail', 'hair', 'hammer', 'hamster', 'hand', 'harbor', 'harp',
  'hawk', 'haze', 'head', 'heart', 'heath', 'hedge', 'helmet', 'hemp', 'herb',
  'hermit', 'heron', 'hickory', 'hill', 'hinge', 'hippo', 'hive', 'hobby',
  'hole', 'hollow', 'holly', 'honey', 'hoof', 'hook', 'hope', 'horn', 'hornet',
  'horse', 'hound', 'hour', 'house', 'hover', 'hub', 'hulk', 'hummingbird',
  'husk', 'hyena', 'ice', 'icon', 'idol', 'igloo', 'image', 'imp', 'incense',
  'index', 'indigo', 'ingot', 'ink', 'insect', 'iron', 'island', 'ivy', 'jacket',
  'jade', 'jaguar', 'jar', 'jasmine', 'javelin', 'jaw', 'jay', 'jazz', 'jeans',
  'jelly', 'jester', 'jet', 'jewel', 'jigsaw', 'joker', 'journey', 'judge',
  'juice', 'jungle', 'junk', 'jury', 'kelp', 'kettle', 'kid', 'king', 'kite',
  'kitten', 'kiwi', 'knife', 'knight', 'knob', 'knot', 'koala', 'kraken', 'label',
  'lace', 'ladder', 'ladle', 'ladybug', 'lagoon', 'lake', 'lamb', 'lamp', 'lance',
  'land', 'lantern', 'lark', 'larva', 'lasso', 'latch', 'lattice', 'laugh',
  'laundry', 'lava', 'lawn', 'leaf', 'leak', 'leash', 'leather', 'leech', 'leek',
  'legend', 'lemon', 'lemur', 'lens', 'leopard', 'lettuce', 'lever', 'lichen',
  'lid', 'light', 'lightning', 'lilac', 'lily', 'limb', 'lime', 'limpet', 'line',
  'link', 'lion', 'liquid', 'lizard', 'loaf', 'lobby', 'lobster', 'lock',
  'locket', 'locust', 'lodge', 'log', 'loop', 'lotus', 'lounge', 'lumber', 'lynx',
  'lyre', 'mace', 'machine', 'maggot', 'magnet', 'magpie', 'mahogany', 'mail',
  'maize', 'mammoth', 'mango', 'manta', 'mantle', 'maple', 'marble', 'mare',
  'marigold', 'marina', 'mark', 'marmot', 'marsh', 'mask', 'mast', 'match',
  'matrix', 'mat', 'mayor', 'meadow', 'meal', 'melon', 'mercury', 'mermaid',
  'mesh', 'metal', 'meteorite', 'microbe', 'milk', 'mill', 'mime', 'mimic',
  'mine', 'mineral', 'minnow', 'mint', 'mire', 'mirror', 'mischief', 'miser',
  'mist', 'mite', 'mitten', 'moat', 'mockingbird', 'mole', 'molt', 'monarch',
  'money', 'mongoose', 'mongrel', 'monitor', 'monkey', 'monster', 'monument',
  'moose', 'mosquito', 'moss', 'moth', 'motion', 'motor', 'mound', 'mountain',
  'mouse', 'mouth', 'movement', 'mower', 'mud', 'muffin', 'mug', 'mulberry',
  'mule', 'mummy', 'muscle', 'mushroom', 'music', 'musket', 'mussel', 'mustang',
  'mustard', 'mutt', 'myrrh', 'mystery', 'myth', 'nail', 'name', 'napkin',
  'narrator', 'narwhal', 'nation', 'nature', 'nautilus', 'nectar', 'needle',
  'nest', 'net', 'newt', 'nexus', 'nickel', 'nightingale', 'node', 'nomad',
  'noodle', 'north', 'nose', 'note', 'novel', 'nozzle', 'nugget', 'numbat',
  'nut', 'nutmeg', 'nylon', 'nymph', 'oak', 'oasis', 'oath', 'oatmeal', 'object',
  'observer', 'obsidian', 'ocean', 'octagon', 'octopus', 'oculot', 'ode', 'ogre',
  'oil', 'ointment', 'okra', 'olive', 'omelet', 'omen', 'onion', 'onyx', 'opal',
  'oracle', 'orange', 'orb', 'orbit', 'orca', 'orchid', 'ore', 'organ', 'origin',
  'oriole', 'ornament', 'orphan', 'osprey', 'ostrich', 'otter', 'outlet', 'oven',
  'overlord', 'owl', 'ox', 'oxygen', 'oyster', 'package', 'paddle', 'page',
  'pail', 'paint', 'palace', 'palm', 'pan', 'panda', 'panel', 'panther', 'pants',
  'papaya', 'paper', 'papyrus', 'parachute', 'parade', 'paradise', 'parasite',
  'parcel', 'parchment', 'park', 'parrot', 'parsley', 'parsnip', 'part',
  'particle', 'partner', 'partridge', 'party', 'pass', 'passage', 'passion',
  'pasta', 'paste', 'pastry', 'patch', 'path', 'patio', 'patrol', 'pattern',
  'paver', 'paw', 'pawn', 'pea', 'peach', 'peak', 'peanut', 'pear', 'pearl',
  'pebble', 'pecan', 'pegasus', 'pelican', 'pelt', 'pen', 'pencil', 'pendulum',
  'penguin', 'penny', 'pepper', 'perch', 'perfume', 'peril', 'petal', 'pet',
  'pewter', 'phantom', 'pharaoh', 'pheasant', 'phial', 'phone', 'phrase', 'piano',
  'pickle', 'picture', 'pie', 'pig', 'pigeon', 'pigment', 'pike', 'pile',
  'pilgrim', 'pillar', 'pillow', 'pilot', 'pimple', 'pin', 'pine', 'pineapple',
  'pioneer', 'pipe', 'piranha', 'pirate', 'piston', 'pit', 'pitch', 'pitcher',
  'pivot', 'pixie', 'pizza', 'plague', 'plain', 'plank', 'plant', 'plasma',
  'plate', 'platform', 'platypus', 'player', 'plaza', 'pleat', 'pliers', 'plot',
  'plow', 'plug', 'plum', 'plumber', 'plume', 'plunger', 'plush', 'pocket',
  'pod', 'poem', 'poet', 'point', 'poison', 'poke', 'pole', 'police', 'polish',
  'pollen', 'polo', 'pond', 'pony', 'pool', 'poppy', 'porcupine', 'port',
  'poster', 'pot', 'potato', 'potter', 'pouch', 'powder', 'power', 'prairie',
  'prawn', 'preacher', 'predator', 'prelude', 'press', 'prey', 'price', 'pride',
  'priest', 'primate', 'prince', 'printer', 'prism', 'prison', 'probe', 'problem',
  'process', 'prodigy', 'professor', 'profile', 'program', 'project', 'prong',
  'prop', 'prophet', 'prospector', 'proton', 'prototype', 'providence', 'prune',
  'psalm', 'pudding', 'puddle', 'puff', 'puffin', 'pug', 'pulp', 'puma', 'pump',
  'pumpkin', 'punch', 'pundit', 'punk', 'pup', 'puppet', 'puppy', 'purge',
  'purse', 'pus', 'puzzle', 'pyramid', 'python', 'quack', 'quail', 'quarry',
  'quarter', 'quartz', 'queen', 'quill', 'quilt', 'quiver', 'quote', 'rabbit',
  'raccoon', 'race', 'rack', 'radar', 'radiator', 'radio', 'radish', 'raft',
  'rage', 'rag', 'rail', 'rain', 'rainbow', 'rake', 'ram', 'rambler', 'rampart',
  'ranch', 'ranger', 'rap', 'raptor', 'raspberry', 'rat', 'ratchet', 'rattler',
  'raven', 'ray', 'razor', 'realm', 'reaper', 'rebel', 'receipt', 'receiver',
  'recipe', 'record', 'recorder', 'rectangle', 'reed', 'reef', 'reel', 'referee',
  'reflection', 'refuge', 'regent', 'reign', 'relic', 'remedy', 'rent', 'repair',
  'reptile', 'republic', 'request', 'reserve', 'reservoir', 'residue', 'resin',
  'resort', 'resource', 'rest', 'result', 'retreat', 'return', 'reunion',
  'reveler', 'revenant', 'review', 'reward', 'rhino', 'rhubarb', 'rhyme',
  'rhythm', 'rib', 'ribbon', 'rice', 'riddle', 'ridge', 'rifle', 'rig', 'right',
  'rim', 'ring', 'riot', 'rip', 'ripple', 'rite', 'ritual', 'river', 'rivet',
  'roach', 'road', 'roast', 'robe', 'robin', 'rock', 'rod', 'rogue', 'role',
  'roll', 'roller', 'romance', 'roof', 'rook', 'room', 'rooster', 'root', 'rope',
  'rose', 'rosemary', 'rotor', 'rouge', 'round', 'route', 'rover', 'row', 'ruby',
  'rudder', 'rug', 'ruin', 'rule', 'ruler', 'rumble', 'rune', 'runner', 'ruse',
  'rush', 'rust', 'rye', 'saber', 'sable', 'sack', 'saddle', 'sadness', 'safe',
  'saffron', 'saga', 'sage', 'sail', 'sailor', 'saint', 'salad', 'salamander',
  'salmon', 'salon', 'salt', 'salute', 'salve', 'samurai', 'sanctuary', 'sand',
  'sandal', 'sandwich', 'sap', 'sapphire', 'sarcasm', 'sardine', 'sash', 'sasquatch',
  'satellite', 'satin', 'satire', 'sauce', 'sauna', 'sausage', 'savant', 'savior',
  'saw', 'saxophone', 'scabbard', 'scale', 'scallop', 'scalp', 'scandal', 'scar',
  'scarf', 'scenario', 'scene', 'scent', 'scepter', 'scheme', 'scholar', 'school',
  'schooner', 'science', 'scimitar', 'scissors', 'scoff', 'scold', 'scone',
  'scoop', 'scope', 'scorpion', 'scout', 'scowl', 'scraper', 'scratch', 'scream',
  'screenplay', 'screw', 'scribe', 'script', 'scythe', 'sea', 'seagull', 'seal',
  'seam', 'seance', 'search', 'seashell', 'season', 'seat', 'seaweed', 'secret',
  'sect', 'sector', 'sedan', 'sedge', 'sediment', 'seed', 'seer', 'segment',
  'seismograph', 'self', 'seller', 'semicircle', 'senator', 'sense', 'sentry',
  'sepulcher', 'serenade', 'serf', 'sergeant', 'series', 'sermon', 'serpent',
  'serum', 'servant', 'server', 'service', 'sesame', 'setting', 'settler',
  'sewer', 'shack', 'shade', 'shadow', 'shaft', 'shaker', 'shale', 'shaman',
  'shame', 'shank', 'shape', 'shard', 'share', 'shark', 'shawl', 'shears',
  'sheath', 'shed', 'sheep', 'sheet', 'shelf', 'shell', 'shelter', 'shepherd',
  'sheriff', 'sherry', 'shilling', 'shine', 'shingle', 'shipwreck', 'shirt',
  'shoal', 'shock', 'shoe', 'shop', 'shore', 'shortcake', 'shot', 'shoulder',
  'shovel', 'show', 'shower', 'shred', 'shrew', 'shriek', 'shrift', 'shrimp',
  'shrine', 'shroud', 'shrub', 'shrug', 'shutter', 'shuttle', 'sickle', 'side',
  'siege', 'sieve', 'sigh', 'sight', 'sign', 'signal', 'signature', 'silence',
  'silk', 'sill', 'silo', 'silver', 'singer', 'siren', 'sirup', 'sister', 'site',
  'skate', 'skeleton', 'skewer', 'ski', 'skid', 'skiff', 'skill', 'skillet',
  'skin', 'skirmish', 'skirt', 'skull', 'skunk', 'skyline', 'slab', 'slack',
  'slag', 'slang', 'slant', 'slap', 'slate', 'slave', 'sled', 'sledge', 'sleep',
  'sleeve', 'slice', 'slick', 'slide', 'slime', 'sling', 'slip', 'slipper',
  'slit', 'slogan', 'slope', 'slot', 'sloth', 'slouch', 'slough', 'slug',
  'sluice', 'slum', 'slump', 'slur', 'smack', 'smash', 'smear', 'smell', 'smile',
  'smirk', 'smith', 'smog', 'smoke', 'smudge', 'snack', 'snag', 'snail', 'snake',
  'snap', 'snare', 'snarl', 'snatch', 'sneak', 'sneer', 'sneeze', 'sniff',
  'snipe', 'snitch', 'snob', 'snoop', 'snore', 'snort', 'snout', 'snow', 'snub',
  'snuff', 'soap', 'sob', 'socket', 'soda', 'sofa', 'soil', 'soldier', 'sole',
  'solitude', 'solo', 'solution', 'sombrero', 'son', 'sonar', 'sonata', 'sonnet',
  'soot', 'sorcerer', 'sorcery', 'sore', 'sorrel', 'sorrow', 'sort', 'soul',
  'sound', 'soup', 'source', 'south', 'souvenir', 'sow', 'space', 'spade',
  'spaghetti', 'span', 'spank', 'spar', 'spark', 'sparrow', 'spasm', 'spat',
  'spatula', 'spawn', 'spear', 'speck', 'spectacle', 'specter', 'spectrum',
  'speech', 'speed', 'spell', 'sphere', 'spice', 'spider', 'spike', 'spill',
  'spin', 'spindle', 'spine', 'spiral', 'spire', 'spirit', 'spit', 'spite',
  'splash', 'spleen', 'splendor', 'splint', 'splinter', 'spoil', 'spoke',
  'sponge', 'spool', 'spoon', 'spore', 'sport', 'spot', 'spout', 'spray',
  'spread', 'spring', 'sprinter', 'sprite', 'sprocket', 'sprout', 'spruce',
  'spur', 'spy', 'squad', 'squalor', 'square', 'squash', 'squat', 'squawk',
  'squeak', 'squeal', 'squeeze', 'squid', 'squint', 'squire', 'squirrel',
  'squirt', 'stab', 'stability', 'stable', 'stack', 'stadium', 'staff', 'stag',
  'stage', 'stain', 'stair', 'stake', 'stalk', 'stall', 'stamen', 'stamina',
  'stamp', 'stance', 'standard', 'staple', 'starfish', 'stark', 'start', 'stash',
  'state', 'station', 'statue', 'status', 'stave', 'steak', 'steam', 'steed',
  'steel', 'stem', 'stench', 'step', 'steppe', 'stereo', 'stern', 'stew',
  'steward', 'stick', 'sticker', 'stigma', 'stile', 'stiletto', 'still', 'stilt',
  'stimulus', 'sting', 'stinger', 'stint', 'stir', 'stirrup', 'stitch', 'stock',
  'stockade', 'stocking', 'stomach', 'stone', 'stool', 'stoop', 'stop', 'stopper',
  'storage', 'store', 'stork', 'storm', 'story', 'stout', 'stove', 'stowaway',
  'strait', 'strand', 'strap', 'strata', 'strategy', 'straw', 'stray', 'streak',
  'streamer', 'street', 'strength', 'stress', 'stretch', 'striker', 'string',
  'strip', 'stripe', 'stroke', 'stroll', 'stronghold', 'structure', 'struggle',
  'strum', 'strut', 'stub', 'stubble', 'student', 'studio', 'study', 'stuff',
  'stump', 'stun', 'stunt', 'stupor', 'sturgeon', 'style', 'stylus', 'subject',
  'submarine', 'substance', 'suburb', 'subway', 'success', 'succotash', 'sucker',
  'suction', 'suede', 'sugar', 'suit', 'sulfur', 'sultan', 'sum', 'summit',
  'summoner', 'sunbeam', 'sundae', 'sundial', 'sunflower', 'sunrise', 'sunset',
  'surf', 'surgeon', 'surgery', 'surplus', 'surprise', 'survey', 'survivor',
  'sushi', 'suspicion', 'swab', 'swallow', 'swamp', 'swan', 'swarm', 'sway',
  'sweat', 'sweater', 'sweep', 'sweet', 'swell', 'swift', 'swim', 'swimmer',
  'swine', 'swing', 'swipe', 'swirl', 'switch', 'swivel', 'swoop', 'symbol',
  'symphony', 'synapse', 'syndicate', 'synergy', 'synod', 'syntax', 'synth',
  'syphon', 'syringe', 'syrup', 'system', 'tab', 'tabby', 'tabernacle', 'table',
  'tablet', 'tabloid', 'taboo', 'tack', 'tackle', 'taco', 'tact', 'tactic',
  'tadpole', 'tag', 'tail', 'tailor', 'taint', 'takeover', 'tale', 'talent',
  'talisman', 'talk', 'talon', 'tambourine', 'tampon', 'tan', 'tandem', 'tang',
  'tangerine', 'tangle', 'tank', 'tanker', 'tap', 'tape', 'taper', 'tapestry',
  'tapioca', 'tar', 'tarantula', 'target', 'tariff', 'tarnish', 'tarot', 'tart',
  'task', 'tassel', 'taste', 'tattoo', 'tavern', 'tax', 'taxi', 'tea', 'teacher',
  'team', 'tear', 'tease', 'technique', 'technology', 'teddy', 'tee', 'teenager',
  'teeth', 'telegram', 'telescope', 'teller', 'temp', 'temper', 'tempest',
  'temple', 'tempo', 'temptation', 'tenant', 'tendency', 'tendon', 'tendril',
  'tennis', 'tenor', 'tension', 'tent', 'tentacle', 'term', 'terminal', 'termite',
  'terrace', 'terrain', 'terrier', 'terror', 'test', 'tester', 'tether', 'text',
  'textbook', 'texture', 'thatch', 'thaw', 'theater', 'theft', 'theme', 'theory',
  'therapist', 'therapy', 'thermal', 'thermos', 'thesaurus', 'thesis', 'thicket',
  'thief', 'thigh', 'thimble', 'thing', 'thirst', 'thistle', 'thong', 'thorn',
  'thought', 'thrall', 'thrash', 'thread', 'threat', 'thrill', 'throne', 'throng',
  'throttle', 'throw', 'thrush', 'thrust', 'thug', 'thumb', 'thump', 'thunder',
  'thyme', 'tiara', 'tick', 'ticket', 'tide', 'tiger', 'tile', 'tilt', 'timber',
  'time', 'timpani', 'tin', 'tinder', 'tinfoil', 'tinge', 'tinker', 'tinsel',
  'tint', 'tip', 'tire', 'tissue', 'titan', 'titanium', 'title', 'toad', 'toast',
  'toaster', 'tobacco', 'today', 'toddler', 'toe', 'toffee', 'toga', 'toggle',
  'toilet', 'toll', 'tomato', 'tomb', 'tome', 'tomorrow', 'ton', 'tone', 'tong',
  'tongue', 'tonic', 'tonight', 'tool', 'tooth', 'top', 'topic', 'torch',
  'torment', 'tornado', 'torpedo', 'torque', 'torrent', 'torso', 'tortoise',
  'torture', 'toss', 'total', 'totem', 'touch', 'tour', 'tournament', 'tow',
  'towel', 'tower', 'town', 'toy', 'trace', 'track', 'tractor', 'trade',
  'tradition', 'tragedy', 'trail', 'trailer', 'train', 'trainer', 'trait',
  'traitor', 'tram', 'tramp', 'trance', 'transfer', 'transform', 'transit',
  'transition', 'translation', 'transmission', 'transmitter', 'trap', 'trapper',
  'trash', 'trauma', 'travel', 'trawl', 'tray', 'treachery', 'tread', 'treasure',
  'treat', 'treatise', 'treaty', 'treble', 'tree', 'trek', 'tremor', 'trench',
  'trend', 'trespass', 'tress', 'trial', 'triangle', 'tribe', 'tribunal',
  'tribute', 'trick', 'trickle', 'trident', 'trifle', 'trigger', 'trill',
  'trilogy', 'trim', 'trinket', 'trip', 'tripe', 'tripod', 'triumph', 'troll',
  'trombone', 'troop', 'trooper', 'trophy', 'trot', 'trouble', 'trough',
  'trousers', 'trout', 'truce', 'truck', 'truffle', 'trumpet', 'trunk', 'truss',
  'trust', 'truth', 'tryst', 'tsunami', 'tub', 'tuba', 'tube', 'tuber', 'tuck',
  'tuft', 'tug', 'tulip', 'tumble', 'tumbler', 'tumor', 'tuna', 'tundra', 'tune',
  'tunic', 'tunnel', 'turban', 'turbine', 'turf', 'turkey', 'turmoil', 'turn',
  'turnip', 'turpentine', 'turret', 'turtle', 'tusk', 'tussle', 'tutor', 'tuxedo',
  'tweak', 'tweed', 'tweet', 'tweezers', 'twelve', 'twenty', 'twig', 'twilight',
  'twine', 'twins', 'twirl', 'twist', 'twitch', 'tycoon', 'typhoon', 'tyrant',
  'udder', 'ulcer', 'umbrella', 'umpire', 'uncle', 'underdog', 'uniform', 'union',
  'unit', 'universe', 'university', 'urchin', 'urn', 'user', 'usher', 'utility',
  'utopia', 'vacuum', 'vagrant', 'valley', 'valor', 'value', 'valve', 'vampire',
  'van', 'vandal', 'vane', 'vanilla', 'vanity', 'vapor', 'variant', 'varnish',
  'vase', 'vat', 'vault', 'veal', 'vector', 'vegetable', 'vehicle', 'veil',
  'vein', 'vellum', 'velvet', 'vendor', 'veneer', 'vengeance', 'venom', 'vent',
  'venture', 'venue', 'veranda', 'verb', 'verdict', 'verge', 'vermin', 'verse',
  'version', 'vertigo', 'vessel', 'vest', 'vestibule', 'veteran', 'veto', 'vial',
  'vicar', 'vice', 'victim', 'video', 'view', 'viewer', 'vigil', 'vigilante',
  'vigor', 'viking', 'village', 'villager', 'vine', 'vinegar', 'vintage',
  'viola', 'violet', 'violin', 'viper', 'virgin', 'virtue', 'visage', 'viscount',
  'vision', 'visit', 'visitor', 'visor', 'vista', 'vitamin', 'vixen', 'vocalist',
  'vodka', 'vogue', 'voice', 'void', 'volcano', 'volt', 'voltage', 'volume',
  'volunteer', 'voodoo', 'vortex', 'vote', 'voter', 'votive', 'vouch', 'voucher',
  'vow', 'vowel', 'voyage', 'voyager', 'vulcan', 'vulture', 'wad', 'waddle',
  'wafer', 'wag', 'wage', 'wagon', 'waif', 'wail', 'waist', 'wait', 'waiter',
  'wake', 'walk', 'walker', 'wall', 'wallet', 'wallflower', 'walnut', 'walrus',
  'waltz', 'wanderer', 'wane', 'want', 'war', 'ward', 'warden', 'wardrobe',
  'warehouse', 'warlord', 'warmth', 'warning', 'warp', 'warrant', 'warrior',
  'wart', 'wash', 'wasp', 'waste', 'watch', 'watchdog', 'watchman', 'water',
  'waterfall', 'watermelon', 'watt', 'wave', 'wax', 'way', 'weakness', 'wealth',
  'weapon', 'weasel', 'weather', 'weave', 'web', 'wedge', 'weed', 'week',
  'weekend', 'weep', 'weevil', 'weight', 'weir', 'weirdo', 'well', 'west',
  'wetland', 'whale', 'wharf', 'wheat', 'wheel', 'whelp', 'whiff', 'whim',
  'whine', 'whip', 'whirl', 'whirlpool', 'whirlwind', 'whisk', 'whisker',
  'whiskey', 'whisper', 'whistle', 'white', 'whittle', 'whoop', 'wick', 'wicket',
  'width', 'wife', 'wig', 'wiggle', 'wigwam', 'wildcat', 'wilderness', 'wildfire',
  'will', 'willow', 'win', 'winch', 'wind', 'windmill', 'window', 'wine', 'wing',
  'wink', 'winner', 'winter', 'wire', 'wisdom', 'wish', 'wisp', 'wit', 'witch',
  'witness', 'wolf', 'woman', 'womb', 'wonder', 'wood', 'woodchuck', 'woodland',
  'woodpecker', 'woods', 'woof', 'wool', 'word', 'work', 'worker', 'workshop',
  'world', 'worm', 'worry', 'worship', 'worth', 'wound', 'wrack', 'wraith',
  'wrangle', 'wrap', 'wrapper', 'wrath', 'wreath', 'wreck', 'wren', 'wrench',
  'wrestler', 'wretch', 'wriggle', 'wrinkle', 'wrist', 'writer', 'writ', 'wrong',
  'xenophobe', 'xylophone', 'yacht', 'yak', 'yam', 'yank', 'yap', 'yard', 'yarn',
  'yawn', 'year', 'yearling', 'yearn', 'yeast', 'yell', 'yellow', 'yelp', 'yen',
  'yeti', 'yield', 'yip', 'yodel', 'yoga', 'yogi', 'yogurt', 'yoke', 'yolk',
  'yore', 'youth', 'zap', 'zeal', 'zealot', 'zebra', 'zenith', 'zephyr', 'zero',
  'zest', 'zeta', 'zinc', 'zing', 'zipper', 'zither', 'zodiac', 'zombie', 'zone',
  'zoo'
];
